import "./globals.css";
import { Poppins } from "next/font/google";
import { Navbar } from "@/app/Components/Navbar";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["500", "800", "400", "200"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className} suppressHydrationWarning={true}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
